# Generated by Django 5.1.4 on 2024-12-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('worker_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='hourly', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period_start', models.DateField()),
                ('payroll_period_end', models.DateField()),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_processed'],
                'unique_together': {('payroll_period_start', 'payroll_period_end')},
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period_start', models.DateField()),
                ('payroll_period_end', models.DateField()),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check')], max_length=20, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='payroll.employee')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-payroll_period_start'],
                'unique_together': {('employee', 'payroll_period_start', 'payroll_period_end')},
            },
        ),
    ]
