# Generated by Django 5.1.4 on 2024-12-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollrun_date_created_payrollrun_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workentry',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('deffered', 'Deferred')], max_length=20, null=True),
        ),
    ]
